import json
import logging
import numpy as np
from scipy.spatial.distance import cdist
from sklearn.mixture import GaussianMixture
from sentence_transformers import SentenceTransformer

# Configure logging
logging.basicConfig(level=logging.INFO, format="%(levelname)s: %(message)s")
logger = logging.getLogger(__name__)


def load_embedding_model(model_name: str = "all-MiniLM-L6-v2", use_gpu: bool = False):
    """
    Loads the HuggingFace embedding model.
    """
    device = "cuda" if use_gpu else "cpu"
    logger.info(f"Loading embedding model: {model_name} on {device}...")
    return SentenceTransformer(model_name, device=device)


def safe_encode(model, texts: list, batch_size: int = 32):
    """
    Generates embeddings for a list of texts.
    """
    logger.info(f"Encoding {len(texts)} text entries...")
    return model.encode(
        texts, batch_size=batch_size, show_progress_bar=True, convert_to_numpy=True
    )


def run_phase2_pipeline(
    micro_json_path: str,
    k_anchors: int = 8,
    model_name: str = "all-MiniLM-L6-v2",
):
    """
    Executes Phase 2: Generating embeddings, discovering K latent anchors via GMM,
    and extracting the best Prototype Quotes for those anchors.
    """
    logger.info(f"Loading Micro-level structured data from {micro_json_path}...")
    with open(micro_json_path, "r", encoding="utf-8") as f:
        micro_data = json.load(f)

    # 1. Extract texts to embed
    # We use the 'processed_text' which has negations bound and typos fixed
    micro_texts = [entry["processed_text"] for entry in micro_data]

    # 2. Generate Global Embeddings
    model = load_embedding_model(model_name=model_name)
    micro_embeddings = safe_encode(model, micro_texts)

    # 3. Unsupervised Anchor Discovery (GMM)
    logger.info(
        f"Fitting Gaussian Mixture Model with K={k_anchors} components on {len(micro_embeddings)} embeddings..."
    )
    # random_state ensures reproducibility across runs
    gmm = GaussianMixture(n_components=k_anchors, random_state=42)
    gmm.fit(micro_embeddings)
    centroids = gmm.means_

    # 4. Find Prototype Quotes (Alternative B)
    logger.info("Discovering Prototype Quotes for latent anchors...")
    anchors = {}

    for k in range(k_anchors):
        centroid = centroids[k]

        # Calculate Euclidean distance from ALL micro embeddings to this specific centroid
        dists = cdist(micro_embeddings, [centroid], metric="euclidean").flatten()
        best_idx = np.argmin(dists)

        # Map the closest embedding back to the original participant's raw text
        prototype_quote = micro_data[best_idx]["raw_text"]
        video_id = micro_data[best_idx]["video_id"]
        participant_id = micro_data[best_idx]["participant_id"]

        anchors[f"Anchor_{k}"] = {
            "id": k,
            "prototype_quote": prototype_quote,
            "source_video_id": video_id,
            "source_participant_id": participant_id,
            "centroid": centroid.tolist(),  # Convert numpy array to list for JSON serialization
        }
        logger.info(
            f"Anchor {k} Prototype: '{prototype_quote}' (from Video {video_id})"
        )

    # 5. Save Outputs for Phase 3
    anchors_out_path = "Analysis/RAG_analysis/phase2_anchors.json"
    with open(anchors_out_path, "w", encoding="utf-8") as f:
        json.dump(anchors, f, indent=2)

    # Save the embeddings array mapping 1:1 to the micro_data list
    embeddings_out_path = "Analysis/RAG_analysis/phase2_micro_embeddings.npy"
    np.save(embeddings_out_path, micro_embeddings)

    logger.info(f"Phase 2 Complete!")
    logger.info(f"Saved anchors to: {anchors_out_path}")
    logger.info(f"Saved embeddings to: {embeddings_out_path}")

    return anchors, micro_embeddings


if __name__ == "__main__":
    # Ensure this points to the exact path generated by Phase 1
    INPUT_MICRO_PATH = "Analysis/RAG_analysis/phase1_micro_level.json"

    # K=8 is a good starting point for discovery, but you can adjust this
    # depending on how many distinct touch categories you hypothesize exist.
    run_phase2_pipeline(micro_json_path=INPUT_MICRO_PATH, k_anchors=8)
